/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    ResultSet rs;
    public Data() {
        initComponents();
        DefaultTableModel tbl = (DefaultTableModel) tblData.getModel();
        DB obj = new DB();
       rs =  obj.selectAll();
       try{
       while(rs.next())
       {
           String data[] = {rs.getString("Id"),rs.getString("FullName"),rs.getString("Email"),rs.getString("Contact"),rs.getString("Gender"),rs.getString("City"),rs.getString("Course")};
           tbl.addRow(data);
           
       }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnDeleteRecord = new javax.swing.JButton();
        btnInsertRecord = new javax.swing.JButton();
        btnUpdateRecord = new javax.swing.JButton();
        btnDelAllRecords = new javax.swing.JButton();
        btnExitTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "FullName", "Email", "Contact", "Gender", "City", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        btnDeleteRecord.setText("Delete Record");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnInsertRecord.setText("Insert Record");
        btnInsertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRecordActionPerformed(evt);
            }
        });

        btnUpdateRecord.setText("Update Record");
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnDelAllRecords.setText("Delete All Records");
        btnDelAllRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAllRecordsActionPerformed(evt);
            }
        });

        btnExitTable.setText("Exit");
        btnExitTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnDeleteRecord)
                .addGap(6, 6, 6)
                .addComponent(btnInsertRecord)
                .addGap(6, 6, 6)
                .addComponent(btnUpdateRecord)
                .addGap(6, 6, 6)
                .addComponent(btnDelAllRecords)
                .addGap(12, 12, 12)
                .addComponent(btnExitTable, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteRecord)
                    .addComponent(btnInsertRecord)
                    .addComponent(btnUpdateRecord)
                    .addComponent(btnDelAllRecords)
                    .addComponent(btnExitTable))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTableActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitTableActionPerformed

    private void btnDelAllRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAllRecordsActionPerformed
        // TODO add your handling code here:
      int num= JOptionPane.showConfirmDialog(this, "Do you really want to delete all Records?");
        System.out.println("yes" + num);
        if(num == 0)
        {
            DB obj = new DB();
            obj.deleteAll();
            JOptionPane.showMessageDialog(this, "Table Records has been deleted!");
            this.dispose();
            new Data().setVisible(true);
        }
        else return;
    }//GEN-LAST:event_btnDelAllRecordsActionPerformed

    private void btnInsertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRecordActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_btnInsertRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
        DB obj = new DB();
        
        if(tblData.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(this, "Select any row!");
            tblData.grabFocus();
            return;
        }
        int num = tblData.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblData.getModel();
        Object numm = tbl.getValueAt(num, 0);
        obj.delSelected(numm);
         JOptionPane.showMessageDialog(this, "Data has been Deleted Successfully");
         this.dispose();
        new Data().setVisible(true);
       
        
        
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        // TODO add your handling code here:
        
        if(tblData.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(this, "Select row you want to update!");
            tblData.grabFocus();
            return;
        }
        int num = tblData.getSelectedRow();
        Object value = tblData.getValueAt(num , 0);
       this.dispose();
                      
        Main man = new Main(5);
        man.setVisible(true);
        man.setValue(value);
        
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelAllRecords;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnExitTable;
    private javax.swing.JButton btnInsertRecord;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
